### PR TITLE
[DONT MERGE] Initial attempt to change project configs to work with our treker.mk instance

### PR DESCRIPTION
**Pull request by trumpets**
TODO Treker-infra
- DONE ZONE_ID (sledilnik/pr-deploy.py) Cloudlfare
- SLACK_WEBHOOK_URL (sledilnik/pr-deploy.py)
- /cert/sledilnik.crt
- /cert/sledilnik.key
- web1?
- DONE cloudflare dns au
- vault.yml

### CODE REVIEW

**Comment by overlordtm** [comment]
So far, LGTM.

* about CF ZONE_ID, I obtained it via python script that lists all zones for given account (wrote it myself, using python cloudflare lib). No idea if you can obtain it any other way. There are multiple different IDs, so play around if it does not work first time
* SLACK_WEBHOOK_URL is used to ping back on slack when deploy is done. Your slack admin can generate webhook URL. If you dont need it, just remove relevant lines from script.
* /cert/sledilnik.crt and /cert/sledilnik.key are fallback certificates for traefik. By default, traefik will try to obtain lets encrypt certs for all domains (that have TLS labels). If it is unable to obtain cert for given domain, it will fallback to certs in folder `/cert`.
https://github.com/treker-mk/infrastructure/blob/3a7225f98cc5c6864e09e2fbbe25a7d23441bdcd/files/traefik/traefik.yml#L15

* web1 is just a name for server. For us, web1.sledilnik.org points to actual IP of server, while sledilnik.org points to Cloudflare (which does the proxying).
* vault.yml contains only value for variable `traefik_auth` in ansible https://github.com/treker-mk/infrastructure/blob/3a7225f98cc5c6864e09e2fbbe25a7d23441bdcd/templates/traefik/docker-compose.yml#L22. File is encrypted (because it contains password to access trafeik dashboard). You can delete this file and generate new one, using ansible-vault https://docs.ansible.com/ansible/latest/user_guide/vault.html

PS: Dont buy certificates, just generate selfsigned one for fallback. In practice, it will never be used :)

**Comment by trumpets** [comment]
@overlordtm Thank you so much for the info Andraz. I still have some follow-ups too, first time using Ansible and Traefik :)

- SLACK_WEBHOOK_URL where should I configure this env variable? In a specific file or in Github Actions?
- Same for the certs? I can generate them, but where do I place the files?
- Do I need to do something to install Traefik or is it automatic in the docker image? After installing (if necessary) do I need to do some manual configs on traefik? And how do I obtain the `traefik_auth` key and what is the format that ansible expects in the vault? `traefik_auth=XXXX` maybe ?

Lastly, our website (with your data, no modifications except for i18n) build successfully right now. Where do I push/run this infra code which listens for the docker images? Do I login to our cloud server at Hetzner? Do we need to perform some manual settings on the cloud server at Hetzner? I guess maybe SLACK_WEBHOOK_URL and the certs go there? :)

Thanks!

**Comment by overlordtm** [comment]
Hi,

## SLACK_WEBHOOK_URL
SLACK_WEBHOOK_URL is used by https://github.com/treker-mk/infrastructure/blob/master/files/sledilnik/pr-deploy.py script only. 

For us, `/opt/sledinik` is root of deploy, so iside this dir, there is `env` file.

```
root@ubuntu-2gb-nbg1-1:/opt/sledilnik# cat env 
export GITHUB_TOKEN=[HIDDEN]
export CF_API_KEY=[HIDDEN]
export SLACK_WEBHOOK_URL=https://hooks.slack.com/services/[HIDDEN]
```

Actually this part is not documented at all, we run scripts in byobu (terminal multiplexer). So you start byobu, open new tab, source `env` file `. /opt/sledilnik/env` and run the script in loop and leave it:

```
while true; do /opt/sledilnik/pr-deploy.py; sleep 60; done
```

Same goes for deploy.sh script. Source env, run it in loop

## Traefik certs 

Certs go to `/opt/traefik/cert/` by default. Location depends on root https://github.com/treker-mk/infrastructure/blob/3a7225f98cc5c6864e09e2fbbe25a7d23441bdcd/traefik.yml#L4

and mounted volume in docker-compose: https://github.com/treker-mk/infrastructure/blob/3a7225f98cc5c6864e09e2fbbe25a7d23441bdcd/templates/traefik/docker-compose.yml#L15

But for start, try without certs. I think it should work, because traefik can obtain certs automatically from lets encrypt

## Trafeik

Trafeik is installed by ansible (this playbook https://github.com/treker-mk/infrastructure/blob/master/traefik.yml). It must be installed before other docker images.

Command is something like this, executed when you are in root of this repo (inventory is folder, containing ansible inventory)
```ansible-playbook -i inventory traefik.yml```

About password for auth, it can be generated following this instructions (htpasswd)
https://docs.traefik.io/middlewares/basicauth/

## Quick setup

1. update all config in this repo (inventory and vault)
2. deploy traefik to server `ansible-playbook -i inventory traefik.yml`
3. deploy sledilnik `ansible-playbook -i inventory sledilnik.yml`
4. create `env` files with secrets (example above)
5. run scripts in byobu

**Comment by trumpets** [comment]
Thank you @overlordtm , that indeed was the missing link! 

Last one probably, do we deploy the https://github.com/treker-mk/data-api in the same way on the cloud?

**Comment by overlordtm** [comment]
Abut data-api, pretty much. It was added later (ad-hoc) so it is not part of this repo (because it just worked, so I did not take any time to document and write deployment scripts).

Basically what I did was to copy the layout of other deployments, put modified `docker-compose` and `deploy.sh` into `/opt/api` and it just works since then :)

deploy.sh for data-api:
```root@ubuntu-2gb-nbg1-1:/opt/api# cat deploy.sh 
#!/bin/bash

# deploy script for green/blue docker-compsoe deploy

DEPLOY_ENV=api

# compare images, switch deploy if newer image exists
CURRENT_IMAGE=$(docker images mihamarkic/slo-covid19-server | grep latest | awk '{print $3}')
docker-compose pull
NEW_IMAGE=$(docker images mihamarkic/slo-covid19-server | grep latest | awk '{print $3}')

if [ "$NEW_IMAGE" = "$CURRENT_IMAGE" ]; then
  echo "No new image available"
  exit 0
else
  echo "New image available, starting deploy"
fi


if [ $(docker ps -f name=prod_blue -q) ]
then
    NEW="green"
    OLD="blue"
else
    NEW="blue"
    OLD="green"
fi

echo "Starting "$NEW" container"
docker-compose --project-name=${DEPLOY_ENV}_${NEW} up -d

echo "Waiting..."
sleep 5s

echo "Stopping "$OLD" container"
docker-compose --project-name=${DEPLOY_ENV}_$OLD stop
```

docker-compose.yml:
```
version: '3.3'

services:
  web:
    image: mihamarkic/slo-covid19-server
    expose:
      - 5000
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.port: 5000
      traefik.http.routers.sledilnikapi.rule: Host(`api.sledilnik.org`)
      traefik.http.routers.sledilnikapi.tls: true

networks:
  traefik:
    external:
      name: lb_traefik
```

**Comment by trumpets** [comment]
@overlordtm Progress!

I believe I'm mostly setup, I just have Ansible hang on me when I run it on the cloud machine.

The machine has everything installed I believe and the vault is properly configured. I am not sure what I am doing wrong.

Command
```
root@ubuntu-2gb-fsn1-1:~/infrastructure# ansible-playbook -i inventory traefik.yml -vvvvv
```

Output
```
ansible-playbook 2.9.9
  config file = /root/infrastructure/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
Using /root/infrastructure/ansible.cfg as config file
Reading vault password file: /root/infrastructure/.vault_pass
setting up inventory plugins
host_list declined parsing /root/infrastructure/inventory/hosts.yml as it did not pass its verify_file() method
script declined parsing /root/infrastructure/inventory/hosts.yml as it did not pass its verify_file() method
Parsed /root/infrastructure/inventory/hosts.yml inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: traefik.yml **********************************************************
Positional arguments: traefik.yml
become_method: sudo
inventory: (u'/root/infrastructure/inventory',)
forks: 5
tags: (u'all',)
verbosity: 5
connection: smart
timeout: 10
1 plays in traefik.yml

PLAY [webservers] **************************************************************

TASK [Gathering Facts] *********************************************************
task path: /root/infrastructure/traefik.yml:2
<web1.treker.mk> ESTABLISH SSH CONNECTION FOR USER: root
<web1.treker.mk> SSH: ansible.cfg set ssh_args: (-C)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<web1.treker.mk> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<web1.treker.mk> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="root")
<web1.treker.mk> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<web1.treker.mk> SSH: PlayContext set ssh_common_args: ()
<web1.treker.mk> SSH: PlayContext set ssh_extra_args: ()
<web1.treker.mk> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/root/.ansible/cp/067f467f43)
<web1.treker.mk> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/067f467f43 web1.treker.mk '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
```

**Comment by trumpets** [comment]
@overlordtm Scratch that :)

It turns out I needed to read up on Ansible and understand how it works. I am running those playbooks on my PC and it setups the remote. 

Which just passed for me. And I've got to say Ansible seems amazing, what an awesome tool to manager remote machines!

I will continue tomorrow and let you know how things go with byobu, first time using it too :)

**Pull request merged**
